# Site settings
title: Avis Clients - Extension WordPress
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Extension pour intégrer les avis de vos clients directement
 au sein de votre site web ! De manière totalement automatique
 les notes et commentaires de vos clients s'intègre à WordPress.
baseurl: "reviews" # the subpath of your site, e.g. /blog/
url: "http://product.pfad.fr" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
